services:
    web:
        build:
            context: ./web
            target: production
        restart: unless-stopped
        env_file:
            - .env
        command: npm run production
        networks:
            - template
        depends_on:
            - api
    api:
        build:
            context: ./api
            target: production
        restart: unless-stopped
        env_file:
            - .env
        command: npm run production
        networks:
            - template
        depends_on:
            - mysql
    mysql:
        image: mysql:8.0
        restart: unless-stopped
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        volumes:
            - mysql:/var/lib/mysql
            - ./database.sql:/docker-entrypoint-initdb.d/init.sql:ro
        ports:
            - 127.0.0.1:${MYSQL_PORT}:3306
        networks:
            - template
volumes:
    mysql:
networks:
    template:
        name: template

