services:
    web:
        build:
            context: ./web
            target: development
        volumes:
            - ./web:/app
            - node_modules_web:/app/node_modules
        restart: unless-stopped
        env_file:
            - .env
        ports:
            - ${WEB_PORT:-80}:80
        command: npm run development
        networks:
            - template
        depends_on:
            - api
    api:
        build:
            context: ./api
            target: development
        restart: unless-stopped
        env_file:
            - .env
        volumes:
            - ./api:/app
            - node_modules_api:/app/node_modules
        ports:
            - ${API_PORT:-3000}:3000
        command: npm run development
        networks:
            - template
        depends_on:
            - postgres
    postgres:
        image: postgres:18-alpine
        restart: unless-stopped
        environment:
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        volumes:
            - postgres:/var/lib/postgresql/data
            - ./database.sql:/docker-entrypoint-initdb.d/init.sql:ro
        ports:
            - 127.0.0.1:${POSTGRES_PORT}:5432
        networks:
            - template
volumes:
    node_modules_web:
    node_modules_api:
    postgres:
networks:
    template:
        name: template
