services:
    web:
        build:
            context: ./web
            target: production
        restart: unless-stopped
        env_file:
            - .env
        command: npm run production
        networks:
            - template
        depends_on:
            - api
    api:
        build:
            context: ./api
            target: production
        restart: unless-stopped
        env_file:
            - .env
        command: npm run production
        networks:
            - template
        depends_on:
            - postgres
    postgres:
        image: postgres:16-alpine
        restart: unless-stopped
        environment:
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        volumes:
            - postgres:/var/lib/postgresql/data
            - ./database.sql:/docker-entrypoint-initdb.d/init.sql:ro
        ports:
            - 127.0.0.1:${POSTGRES_PORT}:5432
        networks:
            - template
volumes:
    postgres:
networks:
    template:
        name: template

