import mysql from 'mysql2/promise';
import mysqldump from 'mysqldump';
import CustomError from './error.js';

/**
 * Shared MySQL driver helper. Models are the only normal production callers.
 */
export default class Mysql {
    static connected = false;
    static connection = null;
    static #rawSqlSentinel = Symbol('raw-sql-fragment');
    static config = {
        host: process.env.MYSQL_HOST || 'mysql',
        user: process.env.MYSQL_USER || 'root',
        password: process.env.MYSQL_ROOT_PASSWORD,
        database: process.env.MYSQL_DATABASE,
        port: Number(process.env.MYSQL_INTERNAL_PORT || 3306),
        multipleStatements: false,
    };

    /**
     * Opens the shared MySQL pool when needed.
     *
     * @param {Record<string, unknown>} config
     * @returns {Promise<typeof Mysql>}
     */
    static async connect(config = {}) {
        if (Mysql.connected) return this;

        Mysql.connection = mysql.createPool({ ...Mysql.config, ...config });
        Mysql.connected = true;
        return this;
    }

    /**
     * Closes the shared MySQL pool.
     *
     * @returns {Promise<typeof Mysql>}
     */
    static async close() {
        if (!Mysql.connected) return this;
        await Mysql.connection.end();
        Mysql.connection = null;
        Mysql.connected = false;
        return this;
    }

    /**
     * Quotes SQL identifiers, including dotted table or column references.
     *
     * @param {string} identifier
     * @returns {string}
     */
    static #quoteIdentifier(identifier) {
        return String(identifier)
            .split('.')
            .map(part => {
                if (part === '*') return '*';
                return `\`${part.replace(/`/g, '``')}\``;
            })
            .join('.');
    }

    /**
     * Validates and sanitizes write payloads by dropping undefined fields.
     *
     * @param {Record<string, unknown>} data
     * @param {string} operation
     * @returns {Record<string, unknown>}
     */
    static #sanitizeWriteData(data, operation) {
        if (!data || typeof data !== 'object' || Array.isArray(data)) {
            throw new CustomError(400, `Invalid data for ${operation} operation.`);
        }

        const sanitized = Object.fromEntries(
            Object.entries(data).filter(([, value]) => value !== undefined)
        );

        if (!Object.keys(sanitized).length) {
            throw new CustomError(400, `No data to ${operation}.`);
        }

        return sanitized;
    }

    /**
     * Executes parameterized SQL generated by this helper.
     *
     * @param {string} sql
     * @param {unknown[]} data
     * @param {{ connection?: import('mysql2/promise').PoolConnection }} context
     * @returns {Promise<unknown>}
     */
    static async #query(sql, data = [], { connection } = {}) {
        if (!connection) {
            await Mysql.connect();
        }

        const executor = connection || Mysql.connection;
        const raw = Mysql.formatRaw(sql, data);
        try {
            const result = await executor.execute(raw.sql.trim(), raw.data);
            return result ? result[0] : result;
        }
        catch (error) {
            throw new CustomError(500, error.message, error);
        }
    }

    /**
     * Inserts one or more rows into a table.
     *
     * @param {string} table
     * @param {Record<string, unknown>|Record<string, unknown>[]} data
     * @param {{ connection?: import('mysql2/promise').PoolConnection }} context
     * @returns {Promise<unknown[]>}
     */
    static async insert(table, data, context = {}) {
        if (!data) {
            throw new CustomError(400, 'Invalid data for insert operation.');
        }
        const rows = Array.isArray(data) ? data : [data];

        return Promise.all(rows.map(row => {
            const sanitizedRow = Mysql.#sanitizeWriteData(row, 'insert');
            const fields = Object.keys(sanitizedRow);
            const values = Object.values(sanitizedRow);
            const fieldSql = fields.map(field => Mysql.#quoteIdentifier(field)).join(',');
            const valueSql = fields.map(() => '?').join(',');
            const sql = `INSERT INTO ${Mysql.#quoteIdentifier(table)} (${fieldSql}) VALUES (${valueSql})`;
            return Mysql.#query(sql, values, context);
        }));
    }

    /**
     * Inserts a row and updates selected fields on duplicate-key conflicts.
     *
     * @param {string} table
     * @param {Record<string, unknown>} data
     * @param {{ conflictFields?: string[], updateFields?: string[] }} options
     * @param {{ connection?: import('mysql2/promise').PoolConnection }} context
     * @returns {Promise<unknown>}
     */
    static async upsert(table, data, { conflictFields = [], updateFields = [] } = {}, context = {}) {
        const sanitizedData = Mysql.#sanitizeWriteData(data, 'upsert');
        const fields = Object.keys(sanitizedData);
        const updatableFields = (updateFields.length ? updateFields : fields)
            .filter(field => !conflictFields.includes(field));

        if (!updatableFields.length) {
            throw new CustomError(400, 'No update fields provided for upsert operation.');
        }

        const fieldSql = fields.map(field => Mysql.#quoteIdentifier(field)).join(',');
        const valueSql = fields.map(() => '?').join(',');
        const updateSql = updatableFields
            .map(field => `${Mysql.#quoteIdentifier(field)} = VALUES(${Mysql.#quoteIdentifier(field)})`)
            .join(', ');
        const sql = `INSERT INTO ${Mysql.#quoteIdentifier(table)} (${fieldSql}) VALUES (${valueSql}) ON DUPLICATE KEY UPDATE ${updateSql}`;

        return Mysql.#query(sql, fields.map(field => sanitizedData[field]), context);
    }

    /**
     * Updates rows by id or by a filter object.
     *
     * @param {string} table
     * @param {Record<string, unknown>} data
     * @param {number|Record<string, unknown>} id
     * @param {{ connection?: import('mysql2/promise').PoolConnection }} context
     * @returns {Promise<unknown>}
     */
    static async update(table, data, id, context = {}) {
        if (!id) {
            throw new CustomError(400, 'No identifier provided for update.');
        }

        data = Mysql.#sanitizeWriteData(data, 'update');

        const values = Object.values(data);
        const fieldsSql = Object.entries(data).map(([field, value], index) => {
            if (value instanceof Date) {
                return `${Mysql.#quoteIdentifier(field)} = ?`;
            }

            if (value !== null && typeof value === 'object') {
                if (Object.hasOwn(value, 'inc')) {
                    values[index] = value.inc;
                    return `${Mysql.#quoteIdentifier(field)} = ${Mysql.#quoteIdentifier(field)} + ?`;
                }
                if (Object.hasOwn(value, 'dec')) {
                    values[index] = value.dec;
                    return `${Mysql.#quoteIdentifier(field)} = ${Mysql.#quoteIdentifier(field)} - ?`;
                }
                if (typeof value.toSqlString === 'function') {
                    values[index] = Mysql.#rawSqlSentinel;
                    return `${Mysql.#quoteIdentifier(field)} = ${value.toSqlString()}`;
                }
                throw new CustomError(400, 'Invalid update operation.');
            }

            return `${Mysql.#quoteIdentifier(field)} = ?`;
        }).join(', ');

        let whereSql = `${Mysql.#quoteIdentifier('id')} = ?`;
        if (typeof id === 'object') {
            const { statement, values: filterValues } = Mysql.getWhereStatements(id);
            whereSql = statement;
            values.push(...filterValues);
        }
        else {
            values.push(id);
        }

        const sql = `UPDATE ${Mysql.#quoteIdentifier(table)} SET ${fieldsSql} WHERE ${whereSql}`;
        return Mysql.#query(sql, values.filter(value => value !== Mysql.#rawSqlSentinel), context);
    }

    /**
     * Deletes rows by id or by a filter object.
     *
     * @param {string} table
     * @param {number|Record<string, unknown>} clause
     * @param {{ limit?: number }} opt
     * @param {{ connection?: import('mysql2/promise').PoolConnection }} context
     * @returns {Promise<unknown>}
     */
    static async delete(table, clause, opt = {}, context = {}) {
        if (!clause) {
            throw new CustomError(400, 'Invalid clause for delete operation.');
        }

        const values = [];
        let whereSql = `${Mysql.#quoteIdentifier('id')} = ?`;
        if (typeof clause === 'object') {
            const where = Mysql.getWhereStatements(clause);
            whereSql = where.statement;
            values.push(...where.values);
        }
        else {
            values.push(clause);
        }

        const limit = opt.limit ? ` LIMIT ${parseInt(opt.limit, 10)}` : '';
        const sql = `DELETE FROM ${Mysql.#quoteIdentifier(table)} WHERE ${whereSql}${limit}`;
        return Mysql.#query(sql, values, context);
    }

    /**
     * Finds rows using filter, projection, ordering, and paging options.
     *
     * @param {string} table
     * @param {{ filter?: Record<string, unknown>, view?: string|string[], opt?: Record<string, unknown> }} options
     * @param {{ connection?: import('mysql2/promise').PoolConnection }} context
     * @returns {Promise<unknown[]>}
     */
    static async find(table, { filter = {}, view = [], opt = {} } = {}, context = {}) {
        if (typeof filter !== 'object' || Array.isArray(filter)) {
            throw new CustomError(400, 'Invalid filter for find operation.');
        }

        view = Array.isArray(view) ? view : [view];
        const viewSql = view.length ? view.map(field => Mysql.#quoteIdentifier(field)).join(',') : '*';

        const { statement, values } = Mysql.getWhereStatements(filter);
        const whereSql = Object.keys(filter).length ? ` WHERE ${statement}` : '';
        const orderSql = opt.order && Object.keys(opt.order).length
            ? ` ORDER BY ${Object.entries(opt.order).map(([field, direction]) => `${Mysql.#quoteIdentifier(field)} ${direction === 1 ? 'ASC' : 'DESC'}`).join(', ')}`
            : '';
        const limitSql = opt.limit ? ` LIMIT ${parseInt(opt.limit, 10)}` : '';
        const offsetSql = opt.skip ? ` OFFSET ${parseInt(opt.skip, 10)}` : '';
        const lockSql = opt.forUpdate ? ' FOR UPDATE' : '';

        const sql = `SELECT ${viewSql} FROM ${Mysql.#quoteIdentifier(table)}${whereSql}${orderSql}${limitSql}${offsetSql}${lockSql}`;
        return Mysql.#query(sql, values, context);
    }

    /**
     * Finds one row or returns null when no row matches.
     *
     * @param {string} table
     * @param {{ filter?: Record<string, unknown>, view?: string|string[], opt?: Record<string, unknown> }} options
     * @param {{ connection?: import('mysql2/promise').PoolConnection }} context
     * @returns {Promise<Record<string, unknown>|null>}
     */
    static async findOne(table, options = {}, context = {}) {
        const rows = await Mysql.find(table, {
            ...options,
            opt: { ...(options.opt || {}), limit: 1 },
        }, context);
        return rows[0] || null;
    }

    /**
     * Gets a single row by id or throws when it is missing.
     *
     * @param {string} table
     * @param {number|string} id
     * @returns {Promise<Record<string, unknown>>}
     */
    static async get(table, id) {
        const row = await Mysql.findOne(table, { filter: { id } });
        if (!row) {
            throw new CustomError(404, 'Item not found.');
        }
        return row;
    }

    /**
     * Builds SQL WHERE snippets and values from a filter object.
     *
     * @param {Record<string, unknown>} filter
     * @returns {{ statement: string, values: unknown[] }}
     */
    static getWhereStatements(filter) {
        const values = [];

        const statement = Object.entries(filter).map(([field, value]) => {
            const quotedField = Mysql.#quoteIdentifier(field);

            if (value === null) {
                return `${quotedField} IS NULL`;
            }

            if (Array.isArray(value)) {
                if (!value.length) return '1=0';
                values.push(...value);
                return `${quotedField} IN (${value.map(() => '?').join(',')})`;
            }

            if (typeof value === 'object') {
                if (Object.hasOwn(value, 'in')) {
                    if (!Array.isArray(value.in) || !value.in.length) return '1=0';
                    values.push(...value.in);
                    return `${quotedField} IN (${value.in.map(() => '?').join(',')})`;
                }
                if (Object.hasOwn(value, 'between')) {
                    values.push(value.between[0], value.between[1]);
                    return `${quotedField} BETWEEN ? AND ?`;
                }
                if (Object.hasOwn(value, 'like')) {
                    values.push(`%${value.like}%`);
                    return `${quotedField} LIKE ?`;
                }
                if (Object.hasOwn(value, 'not')) {
                    if (value.not === null) {
                        return `${quotedField} IS NOT NULL`;
                    }
                    values.push(value.not);
                    return `${quotedField} != ?`;
                }

                const operator = Object.keys(value)[0];
                if (!['<', '<=', '>', '>='].includes(operator)) {
                    throw new CustomError(400, 'Invalid filter operation.');
                }
                values.push(value[operator]);
                return `${quotedField} ${operator} ?`;
            }

            values.push(value);
            return `${quotedField} = ?`;
        }).join(' AND ');

        return { statement, values };
    }

    /**
     * Resets tables for integration tests while keeping SQL centralized here.
     *
     * @param {string[]} tables
     * @returns {Promise<void>}
     */
    static async resetTables(tables) {
        await Mysql.connect();
        await Mysql.#query('SET FOREIGN_KEY_CHECKS = 0', []);
        for (const table of tables) {
            await Mysql.#query(`TRUNCATE TABLE ${Mysql.#quoteIdentifier(table)}`, []);
        }
        await Mysql.#query('SET FOREIGN_KEY_CHECKS = 1', []);
    }

    /**
     * Runs an operation in a transaction using a dedicated pool connection.
     *
     * @template T
     * @param {(context: { connection: import('mysql2/promise').PoolConnection }) => Promise<T>} operation
     * @returns {Promise<T>}
     */
    static async withTransaction(operation) {
        await Mysql.connect();
        const connection = await Mysql.connection.getConnection();

        try {
            await connection.beginTransaction();
            const result = await operation({ connection });
            await connection.commit();
            return result;
        }
        catch (error) {
            await connection.rollback();
            throw error;
        }
        finally {
            connection.release();
        }
    }

    /**
     * Wraps trusted SQL so it can be embedded in generated statements.
     *
     * @param {string} sql
     * @returns {{ toSqlString: () => string }}
     */
    static raw(sql) {
        return { toSqlString: () => sql };
    }

    /**
     * Removes raw SQL fragments from the placeholder data before execution.
     *
     * @param {string} sql
     * @param {unknown[]} data
     * @returns {{ sql: string, data: unknown[] }}
     */
    static formatRaw(sql, data = []) {
        const originalSql = sql;
        const pieces = sql.split('?');

        if (pieces.length > 1) {
            let joinedSql = pieces.shift();

            try {
                data.forEach(value => {
                    joinedSql += value && typeof value.toSqlString === 'function'
                        ? value.toSqlString()
                        : '?';
                    joinedSql += pieces.shift();
                });
                sql = joinedSql;
            }
            catch {
                sql = originalSql;
            }

            data = Array.isArray(data)
                ? data.filter(value => !value || typeof value.toSqlString !== 'function')
                : data;
        }

        return { sql, data };
    }

    /**
     * Delegates SQL formatting to the active mysql2 pool.
     *
     * @param {string} sql
     * @param {unknown[]} data
     * @returns {string}
     */
    static format(sql, data = []) {
        if (!Mysql.connection) {
            throw new CustomError(500, 'Database not connected.');
        }
        return Mysql.connection.format(sql, data);
    }

    /**
     * Converts a timestamp-like value into MySQL DATETIME format.
     *
     * @param {string|number|Date} timestamp
     * @returns {string}
     */
    static toDateTime(timestamp) {
        return new Date(timestamp).toISOString().replace('T', ' ').replace('Z', '');
    }

    /**
     * Dumps the configured database to a file using mysqldump.
     *
     * @param {string} path
     * @param {Record<string, unknown>} options
     * @returns {Promise<unknown>}
     */
    static async dump(path, options = {}) {
        return mysqldump({
            connection: Mysql.config,
            dumpToFile: path,
            ...options,
        });
    }

    static like(str) {
        return { like: str };
    }

    static between(a, b) {
        return { between: [a, b] };
    }

    static ne(value) {
        return { not: value };
    }

    static lt(value) {
        return { '<': value };
    }

    static gt(value) {
        return { '>': value };
    }

    static lte(value) {
        return { '<=': value };
    }

    static gte(value) {
        return { '>=': value };
    }
}
