import mysql from 'mysql2/promise';
import CustomError from './error.js';

/**
 * Shared MySQL driver helper. Models are the only normal production callers.
 */
export default class Mysql {
    static connected = false;
    static connection = null;
    static config = {
        host: process.env.MYSQL_HOST || 'mysql',
        user: process.env.MYSQL_USER || 'root',
        password: process.env.MYSQL_ROOT_PASSWORD,
        database: process.env.MYSQL_DATABASE,
        port: Number(process.env.MYSQL_INTERNAL_PORT || 3306),
        multipleStatements: false,
    };

    /**
     * Opens the shared MySQL pool when needed.
     *
     * @param {Record<string, unknown>} config
     * @returns {Promise<typeof Mysql>}
     */
    static async connect(config = {}) {
        if (Mysql.connected) return this;

        Mysql.connection = mysql.createPool({ ...Mysql.config, ...config });
        Mysql.connected = true;
        return this;
    }

    /**
     * Closes the shared MySQL pool.
     *
     * @returns {Promise<typeof Mysql>}
     */
    static async close() {
        if (!Mysql.connected) return this;
        await Mysql.connection.end();
        Mysql.connection = null;
        Mysql.connected = false;
        return this;
    }

    /**
     * Quotes SQL identifiers, including dotted table or column references.
     *
     * @param {string} identifier
     * @returns {string}
     */
    static #quoteIdentifier(identifier) {
        return String(identifier)
            .split('.')
            .map(part => {
                if (part === '*') return '*';
                return `\`${part.replace(/`/g, '``')}\``;
            })
            .join('.');
    }

    /**
     * Executes parameterized SQL generated by this helper.
     *
     * @param {string} sql
     * @param {unknown[]} data
     * @returns {Promise<unknown>}
     */
    static async #query(sql, data = []) {
        await Mysql.connect();

        try {
            const result = await Mysql.connection.execute(sql.trim(), data);
            return result ? result[0] : result;
        }
        catch (error) {
            throw new CustomError(500, error.message, error);
        }
    }

    /**
     * Inserts one or more rows into a table.
     *
     * @param {string} table
     * @param {Record<string, unknown>|Record<string, unknown>[]} data
     * @returns {Promise<unknown[]>}
     */
    static async insert(table, data) {
        if (!data) {
            throw new CustomError(400, 'Invalid data for insert operation.');
        }
        const rows = Array.isArray(data) ? data : [data];

        return Promise.all(rows.map(row => {
            const fields = Object.keys(row);
            if (!fields.length) {
                throw new CustomError(400, 'Invalid data for insert operation.');
            }

            const values = Object.values(row);
            const fieldSql = fields.map(field => Mysql.#quoteIdentifier(field)).join(',');
            const valueSql = fields.map(() => '?').join(',');
            const sql = `INSERT INTO ${Mysql.#quoteIdentifier(table)} (${fieldSql}) VALUES (${valueSql})`;
            return Mysql.#query(sql, values);
        }));
    }

    /**
     * Updates rows by id or by a filter object.
     *
     * @param {string} table
     * @param {Record<string, unknown>} data
     * @param {number|Record<string, unknown>} id
     * @returns {Promise<unknown>}
     */
    static async update(table, data, id) {
        if (!id) {
            throw new CustomError(400, 'No identifier provided for update.');
        }

        data = Object.fromEntries(Object.entries(data || {}).filter(([, value]) => value !== undefined));
        if (!Object.keys(data).length) {
            throw new CustomError(400, 'No data to update.');
        }

        const values = Object.values(data);
        const fieldsSql = Object.entries(data).map(([field, value], index) => {
            if (value !== null && typeof value === 'object') {
                if (Object.hasOwn(value, 'inc')) {
                    values[index] = value.inc;
                    return `${Mysql.#quoteIdentifier(field)} = ${Mysql.#quoteIdentifier(field)} + ?`;
                }
                if (Object.hasOwn(value, 'dec')) {
                    values[index] = value.dec;
                    return `${Mysql.#quoteIdentifier(field)} = ${Mysql.#quoteIdentifier(field)} - ?`;
                }
                throw new CustomError(400, 'Invalid update operation.');
            }

            return `${Mysql.#quoteIdentifier(field)} = ?`;
        }).join(', ');

        let whereSql = `${Mysql.#quoteIdentifier('id')} = ?`;
        if (typeof id === 'object') {
            const { statement, values: filterValues } = Mysql.getWhereStatements(id);
            whereSql = statement;
            values.push(...filterValues);
        }
        else {
            values.push(id);
        }

        const sql = `UPDATE ${Mysql.#quoteIdentifier(table)} SET ${fieldsSql} WHERE ${whereSql}`;
        return Mysql.#query(sql, values);
    }

    /**
     * Deletes rows by id or by a filter object.
     *
     * @param {string} table
     * @param {number|Record<string, unknown>} clause
     * @param {{ limit?: number }} opt
     * @returns {Promise<unknown>}
     */
    static async delete(table, clause, opt = {}) {
        if (!clause) {
            throw new CustomError(400, 'Invalid clause for delete operation.');
        }

        const values = [];
        let whereSql = `${Mysql.#quoteIdentifier('id')} = ?`;
        if (typeof clause === 'object') {
            const where = Mysql.getWhereStatements(clause);
            whereSql = where.statement;
            values.push(...where.values);
        }
        else {
            values.push(clause);
        }

        const limit = opt.limit ? ` LIMIT ${parseInt(opt.limit, 10)}` : '';
        const sql = `DELETE FROM ${Mysql.#quoteIdentifier(table)} WHERE ${whereSql}${limit}`;
        return Mysql.#query(sql, values);
    }

    /**
     * Finds rows using filter, projection, ordering, and paging options.
     *
     * @param {string} table
     * @param {{ filter?: Record<string, unknown>, view?: string|string[], opt?: Record<string, unknown> }} options
     * @returns {Promise<unknown[]>}
     */
    static async find(table, { filter = {}, view = [], opt = {} } = {}) {
        if (typeof filter !== 'object' || Array.isArray(filter)) {
            throw new CustomError(400, 'Invalid filter for find operation.');
        }

        view = Array.isArray(view) ? view : [view];
        const viewSql = view.length ? view.map(field => Mysql.#quoteIdentifier(field)).join(',') : '*';

        const { statement, values } = Mysql.getWhereStatements(filter);
        const whereSql = Object.keys(filter).length ? ` WHERE ${statement}` : '';
        const orderSql = opt.order
            ? ` ORDER BY ${Mysql.#quoteIdentifier(Object.keys(opt.order)[0])} ${Object.values(opt.order)[0] === 1 ? 'ASC' : 'DESC'}`
            : '';
        const limitSql = opt.limit ? ` LIMIT ${parseInt(opt.limit, 10)}` : '';
        const offsetSql = opt.skip ? ` OFFSET ${parseInt(opt.skip, 10)}` : '';

        const sql = `SELECT ${viewSql} FROM ${Mysql.#quoteIdentifier(table)}${whereSql}${orderSql}${limitSql}${offsetSql}`;
        return Mysql.#query(sql, values);
    }

    /**
     * Gets a single row by id or throws when it is missing.
     *
     * @param {string} table
     * @param {number} id
     * @returns {Promise<Record<string, unknown>>}
     */
    static async get(table, id) {
        const rows = await Mysql.find(table, { filter: { id }, opt: { limit: 1 } });
        if (!rows.length) {
            throw new CustomError(404, 'Item not found.');
        }
        return rows[0];
    }

    /**
     * Builds SQL WHERE snippets and values from a filter object.
     *
     * @param {Record<string, unknown>} filter
     * @returns {{ statement: string, values: unknown[] }}
     */
    static getWhereStatements(filter) {
        const values = [];

        const statement = Object.entries(filter).map(([field, value]) => {
            const quotedField = Mysql.#quoteIdentifier(field);

            if (value === null) {
                return `${quotedField} IS NULL`;
            }

            if (Array.isArray(value)) {
                if (!value.length) return '1=0';
                values.push(...value);
                return `${quotedField} IN (${value.map(() => '?').join(',')})`;
            }

            if (typeof value === 'object') {
                if (Object.hasOwn(value, 'in')) {
                    if (!Array.isArray(value.in) || !value.in.length) return '1=0';
                    values.push(...value.in);
                    return `${quotedField} IN (${value.in.map(() => '?').join(',')})`;
                }
                if (Object.hasOwn(value, 'between')) {
                    values.push(value.between[0], value.between[1]);
                    return `${quotedField} BETWEEN ? AND ?`;
                }
                if (Object.hasOwn(value, 'like')) {
                    values.push(`%${value.like}%`);
                    return `${quotedField} LIKE ?`;
                }
                if (Object.hasOwn(value, 'not')) {
                    if (value.not === null) {
                        return `${quotedField} IS NOT NULL`;
                    }
                    values.push(value.not);
                    return `${quotedField} != ?`;
                }

                const operator = Object.keys(value)[0];
                if (!['<', '<=', '>', '>='].includes(operator)) {
                    throw new CustomError(400, 'Invalid filter operation.');
                }
                values.push(value[operator]);
                return `${quotedField} ${operator} ?`;
            }

            values.push(value);
            return `${quotedField} = ?`;
        }).join(' AND ');

        return { statement, values };
    }

    /**
     * Resets tables for integration tests while keeping SQL centralized here.
     *
     * @param {string[]} tables
     * @returns {Promise<void>}
     */
    static async resetTables(tables) {
        await Mysql.connect();
        await Mysql.#query('SET FOREIGN_KEY_CHECKS = 0', []);
        for (const table of tables) {
            await Mysql.#query(`TRUNCATE TABLE ${Mysql.#quoteIdentifier(table)}`, []);
        }
        await Mysql.#query('SET FOREIGN_KEY_CHECKS = 1', []);
    }

    static like(str) {
        return { like: str };
    }

    static between(a, b) {
        return { between: [a, b] };
    }

    static ne(value) {
        return { not: value };
    }

    static lt(value) {
        return { '<': value };
    }

    static gt(value) {
        return { '>': value };
    }

    static lte(value) {
        return { '<=': value };
    }

    static gte(value) {
        return { '>=': value };
    }
}
