import pg from 'pg';
import { CustomError } from './error.js';

const { Pool } = pg;

/**
 * Shared PostgreSQL driver helper. Models are the only normal production callers.
 */
export class Postgres {
    static connected = false;
    static connection = null;
    static #rawSqlSentinel = Symbol('raw-sql-fragment');
    static get config() {
        const host = process.env.POSTGRES_HOST || 'postgres';
        const isContainer = host === 'postgres';
        return {
            host,
            user: process.env.POSTGRES_USER || 'postgres',
            password: process.env.POSTGRES_PASSWORD,
            database: process.env.POSTGRES_DB,
            port: Number(isContainer ? (process.env.POSTGRES_CONTAINER_PORT || 5432) : (process.env.POSTGRES_PORT || 5432)),
        };
    }

    /**
     * Opens the shared PostgreSQL pool when needed.
     *
     * @param {Record<string, unknown>} config
     * @returns {Promise<typeof Postgres>}
     */
    static async connect(config = {}) {
        if (Postgres.connected) return this;

        Postgres.connection = new Pool({ ...Postgres.config, ...config });
        Postgres.connected = true;
        return this;
    }

    /**
     * Closes the shared PostgreSQL pool.
     *
     * @returns {Promise<typeof Postgres>}
     */
    static async close() {
        if (!Postgres.connected) return this;
        await Postgres.connection.end();
        Postgres.connection = null;
        Postgres.connected = false;
        return this;
    }

    /**
     * Quotes SQL identifiers using double quotes, handling dotted table or column references.
     *
     * @param {string} identifier
     * @returns {string}
     */
    static #quoteIdentifier(identifier) {
        return String(identifier)
            .split('.')
            .map(part => {
                if (part === '*') return '*';
                return `"${part.replace(/"/g, '""')}"`;
            })
            .join('.');
    }

    /**
     * Validates and sanitizes write payloads by dropping undefined fields.
     *
     * @param {Record<string, unknown>} data
     * @param {string} operation
     * @returns {Record<string, unknown>}
     */
    static #sanitizeWriteData(data, operation) {
        if (!data || typeof data !== 'object' || Array.isArray(data)) {
            throw new CustomError(400, `Invalid data for ${operation} operation.`);
        }

        const sanitized = Object.fromEntries(
            Object.entries(data).filter(([, value]) => value !== undefined)
        );

        if (!Object.keys(sanitized).length) {
            throw new CustomError(400, `No data to ${operation}.`);
        }

        return sanitized;
    }

    /**
     * Converts ? placeholders in SQL queries into PostgreSQL $1, $2, ... format.
     *
     * @param {string} sql
     * @returns {string}
     */
    static #convertPlaceholders(sql) {
        let paramIndex = 1;
        return sql.replace(/\?/g, () => `$${paramIndex++}`);
    }

    /**
     * Executes parameterized SQL generated by this helper.
     *
     * @param {string} sql
     * @param {unknown[]} data
     * @param {{ connection?: import('pg').PoolClient }} context
     * @returns {Promise<unknown[]>}
     */
    static async #query(sql, data = [], { connection } = {}) {
        if (!connection) {
            await Postgres.connect();
        }

        const executor = connection || Postgres.connection;
        const raw = Postgres.formatRaw(sql, data);
        const pgSql = Postgres.#convertPlaceholders(raw.sql.trim());

        try {
            const result = await executor.query(pgSql, raw.data);
            const rows = (result.rows || []).map(row => {
                if (row && typeof row === 'object' && !('insertId' in row) && 'id' in row) {
                    Object.defineProperty(row, 'insertId', {
                        get() {
                            return this.id;
                        },
                        enumerable: false,
                        configurable: true,
                    });
                }
                return row;
            });
            return rows;
        }
        catch (error) {
            throw new CustomError(500, error.message, error);
        }
    }

    /**
     * Inserts one or more rows into a table.
     *
     * @param {string} table
     * @param {Record<string, unknown>|Record<string, unknown>[]} data
     * @param {{ connection?: import('pg').PoolClient }} context
     * @returns {Promise<unknown[]>}
     */
    static async insert(table, data, context = {}) {
        if (!data) {
            throw new CustomError(400, 'Invalid data for insert operation.');
        }
        const rows = Array.isArray(data) ? data : [data];

        return Promise.all(rows.map(async row => {
            const sanitizedRow = Postgres.#sanitizeWriteData(row, 'insert');
            const fields = Object.keys(sanitizedRow);
            const values = Object.values(sanitizedRow);
            const fieldSql = fields.map(field => Postgres.#quoteIdentifier(field)).join(',');
            const valueSql = fields.map(() => '?').join(',');
            const sql = `INSERT INTO ${Postgres.#quoteIdentifier(table)} (${fieldSql}) VALUES (${valueSql}) RETURNING *`;
            const result = await Postgres.#query(sql, values, context);
            return result;
        }));
    }

    /**
     * Inserts a row and updates selected fields on conflict.
     *
     * @param {string} table
     * @param {Record<string, unknown>} data
     * @param {{ conflictFields?: string[], updateFields?: string[] }} options
     * @param {{ connection?: import('pg').PoolClient }} context
     * @returns {Promise<unknown[]>}
     */
    static async upsert(table, data, { conflictFields = [], updateFields = [] } = {}, context = {}) {
        const sanitizedData = Postgres.#sanitizeWriteData(data, 'upsert');
        const fields = Object.keys(sanitizedData);
        const updatableFields = (updateFields.length ? updateFields : fields)
            .filter(field => !conflictFields.includes(field));

        if (!updatableFields.length) {
            throw new CustomError(400, 'No update fields provided for upsert operation.');
        }

        const conflictTarget = conflictFields.length
            ? conflictFields.map(f => Postgres.#quoteIdentifier(f)).join(', ')
            : Postgres.#quoteIdentifier('id');

        const fieldSql = fields.map(field => Postgres.#quoteIdentifier(field)).join(',');
        const valueSql = fields.map(() => '?').join(',');
        const updateSql = updatableFields
            .map(field => `${Postgres.#quoteIdentifier(field)} = EXCLUDED.${Postgres.#quoteIdentifier(field)}`)
            .join(', ');
        const sql = `INSERT INTO ${Postgres.#quoteIdentifier(table)} (${fieldSql}) VALUES (${valueSql}) ON CONFLICT (${conflictTarget}) DO UPDATE SET ${updateSql} RETURNING *`;

        return Postgres.#query(sql, fields.map(field => sanitizedData[field]), context);
    }

    /**
     * Updates rows by id or by a filter object.
     *
     * @param {string} table
     * @param {Record<string, unknown>} data
     * @param {number|Record<string, unknown>} id
     * @param {{ connection?: import('pg').PoolClient }} context
     * @returns {Promise<unknown[]>}
     */
    static async update(table, data, id, context = {}) {
        if (!id) {
            throw new CustomError(400, 'No identifier provided for update.');
        }

        data = Postgres.#sanitizeWriteData(data, 'update');

        const values = Object.values(data);
        const fieldsSql = Object.entries(data).map(([field, value], index) => {
            if (value instanceof Date) {
                return `${Postgres.#quoteIdentifier(field)} = ?`;
            }

            if (value !== null && typeof value === 'object') {
                if (Object.hasOwn(value, 'inc')) {
                    values[index] = value.inc;
                    return `${Postgres.#quoteIdentifier(field)} = ${Postgres.#quoteIdentifier(field)} + ?`;
                }
                if (Object.hasOwn(value, 'dec')) {
                    values[index] = value.dec;
                    return `${Postgres.#quoteIdentifier(field)} = ${Postgres.#quoteIdentifier(field)} - ?`;
                }
                if (typeof value.toSqlString === 'function') {
                    values[index] = Postgres.#rawSqlSentinel;
                    return `${Postgres.#quoteIdentifier(field)} = ${value.toSqlString()}`;
                }
                throw new CustomError(400, 'Invalid update operation.');
            }

            return `${Postgres.#quoteIdentifier(field)} = ?`;
        }).join(', ');

        let whereSql = `${Postgres.#quoteIdentifier('id')} = ?`;
        if (typeof id === 'object') {
            const { statement, values: filterValues } = Postgres.getWhereStatements(id);
            whereSql = statement;
            values.push(...filterValues);
        }
        else {
            values.push(id);
        }

        const sql = `UPDATE ${Postgres.#quoteIdentifier(table)} SET ${fieldsSql} WHERE ${whereSql} RETURNING *`;
        return Postgres.#query(sql, values.filter(value => value !== Postgres.#rawSqlSentinel), context);
    }

    /**
     * Deletes rows by id or by a filter object.
     *
     * @param {string} table
     * @param {number|Record<string, unknown>} clause
     * @param {{ limit?: number }} opt
     * @param {{ connection?: import('pg').PoolClient }} context
     * @returns {Promise<unknown[]>}
     */
    static async delete(table, clause, opt = {}, context = {}) {
        if (!clause) {
            throw new CustomError(400, 'Invalid clause for delete operation.');
        }

        const values = [];
        let whereSql = `${Postgres.#quoteIdentifier('id')} = ?`;
        if (typeof clause === 'object') {
            const where = Postgres.getWhereStatements(clause);
            whereSql = where.statement;
            values.push(...where.values);
        }
        else {
            values.push(clause);
        }

        let sql;
        if (opt.limit) {
            const limit = parseInt(opt.limit, 10);
            sql = `DELETE FROM ${Postgres.#quoteIdentifier(table)} WHERE ${Postgres.#quoteIdentifier('id')} IN (SELECT ${Postgres.#quoteIdentifier('id')} FROM ${Postgres.#quoteIdentifier(table)} WHERE ${whereSql} LIMIT ${limit})`;
        } else {
            sql = `DELETE FROM ${Postgres.#quoteIdentifier(table)} WHERE ${whereSql}`;
        }

        return Postgres.#query(sql, values, context);
    }

    /**
     * Finds rows using filter, projection, ordering, and paging options.
     *
     * @param {string} table
     * @param {{ filter?: Record<string, unknown>, view?: string|string[], opt?: Record<string, unknown> }} options
     * @param {{ connection?: import('pg').PoolClient }} context
     * @returns {Promise<unknown[]>}
     */
    static async find(table, { filter = {}, view = [], opt = {} } = {}, context = {}) {
        if (typeof filter !== 'object' || Array.isArray(filter)) {
            throw new CustomError(400, 'Invalid filter for find operation.');
        }

        view = Array.isArray(view) ? view : [view];
        const viewSql = view.length ? view.map(field => Postgres.#quoteIdentifier(field)).join(',') : '*';

        const { statement, values } = Postgres.getWhereStatements(filter);
        const whereSql = Object.keys(filter).length ? ` WHERE ${statement}` : '';
        const orderSql = opt.order && Object.keys(opt.order).length
            ? ` ORDER BY ${Object.entries(opt.order).map(([field, direction]) => `${Postgres.#quoteIdentifier(field)} ${direction === 1 ? 'ASC' : 'DESC'}`).join(', ')}`
            : '';
        const limitSql = opt.limit ? ` LIMIT ${parseInt(opt.limit, 10)}` : '';
        const offsetSql = opt.skip ? ` OFFSET ${parseInt(opt.skip, 10)}` : '';
        const lockSql = opt.forUpdate ? ' FOR UPDATE' : '';

        const sql = `SELECT ${viewSql} FROM ${Postgres.#quoteIdentifier(table)}${whereSql}${orderSql}${limitSql}${offsetSql}${lockSql}`;
        return Postgres.#query(sql, values, context);
    }

    /**
     * Finds one row or returns null when no row matches.
     *
     * @param {string} table
     * @param {{ filter?: Record<string, unknown>, view?: string|string[], opt?: Record<string, unknown> }} options
     * @param {{ connection?: import('pg').PoolClient }} context
     * @returns {Promise<Record<string, unknown>|null>}
     */
    static async findOne(table, options = {}, context = {}) {
        const rows = await Postgres.find(table, {
            ...options,
            opt: { ...(options.opt || {}), limit: 1 },
        }, context);
        return rows[0] || null;
    }

    /**
     * Gets a single row by id or throws when it is missing.
     *
     * @param {string} table
     * @param {number|string} id
     * @returns {Promise<Record<string, unknown>>}
     */
    static async get(table, id) {
        const row = await Postgres.findOne(table, { filter: { id } });
        if (!row) {
            throw new CustomError(404, 'Item not found.', 'ITEM_NOT_FOUND');
        }
        return row;
    }

    /**
     * Builds SQL WHERE snippets and values from a filter object.
     *
     * @param {Record<string, unknown>} filter
     * @returns {{ statement: string, values: unknown[] }}
     */
    static getWhereStatements(filter) {
        const values = [];

        const statement = Object.entries(filter).map(([field, value]) => {
            const quotedField = Postgres.#quoteIdentifier(field);

            if (value === null) {
                return `${quotedField} IS NULL`;
            }

            if (Array.isArray(value)) {
                if (!value.length) return '1=0';
                values.push(...value);
                return `${quotedField} IN (${value.map(() => '?').join(',')})`;
            }

            if (typeof value === 'object') {
                if (Object.hasOwn(value, 'in')) {
                    if (!Array.isArray(value.in) || !value.in.length) return '1=0';
                    values.push(...value.in);
                    return `${quotedField} IN (${value.in.map(() => '?').join(',')})`;
                }
                if (Object.hasOwn(value, 'between')) {
                    values.push(value.between[0], value.between[1]);
                    return `${quotedField} BETWEEN ? AND ?`;
                }
                if (Object.hasOwn(value, 'like')) {
                    values.push(`%${value.like}%`);
                    return `${quotedField} LIKE ?`;
                }
                if (Object.hasOwn(value, 'not')) {
                    if (value.not === null) {
                        return `${quotedField} IS NOT NULL`;
                    }
                    values.push(value.not);
                    return `${quotedField} != ?`;
                }

                const operator = Object.keys(value)[0];
                if (!['<', '<=', '>', '>='].includes(operator)) {
                    throw new CustomError(400, 'Invalid filter operation.');
                }
                values.push(value[operator]);
                return `${quotedField} ${operator} ?`;
            }

            values.push(value);
            return `${quotedField} = ?`;
        }).join(' AND ');

        return { statement, values };
    }

    /**
     * Resets tables for integration tests.
     *
     * @param {string[]} tables
     * @returns {Promise<void>}
     */
    static async resetTables(tables) {
        await Postgres.connect();
        for (const table of tables) {
            await Postgres.#query(`TRUNCATE TABLE ${Postgres.#quoteIdentifier(table)} RESTART IDENTITY CASCADE`, []);
        }
    }

    /**
     * Runs an operation in a transaction using a dedicated pool client.
     *
     * @template T
     * @param {(context: { connection: import('pg').PoolClient }) => Promise<T>} operation
     * @returns {Promise<T>}
     */
    static async withTransaction(operation) {
        await Postgres.connect();
        const client = await Postgres.connection.connect();

        try {
            await client.query('BEGIN');
            const result = await operation({ connection: client });
            await client.query('COMMIT');
            return result;
        }
        catch (error) {
            await client.query('ROLLBACK');
            throw error;
        }
        finally {
            client.release();
        }
    }

    /**
     * Wraps trusted SQL so it can be embedded in generated statements.
     *
     * @param {string} sql
     * @returns {{ toSqlString: () => string }}
     */
    static raw(sql) {
        return { toSqlString: () => sql };
    }

    /**
     * Removes raw SQL fragments from the placeholder data before execution.
     *
     * @param {string} sql
     * @param {unknown[]} data
     * @returns {{ sql: string, data: unknown[] }}
     */
    static formatRaw(sql, data = []) {
        const originalSql = sql;
        const pieces = sql.split('?');

        if (pieces.length > 1) {
            let joinedSql = pieces.shift();

            try {
                data.forEach(value => {
                    joinedSql += value && typeof value.toSqlString === 'function'
                        ? value.toSqlString()
                        : '?';
                    joinedSql += pieces.shift();
                });
                sql = joinedSql;
            }
            catch {
                sql = originalSql;
            }

            data = Array.isArray(data)
                ? data.filter(value => !value || typeof value.toSqlString !== 'function')
                : data;
        }

        return { sql, data };
    }

    /**
     * Formats SQL statement with values for debugging.
     *
     * @param {string} sql
     * @param {unknown[]} data
     * @returns {string}
     */
    static format(sql, data = []) {
        let formatted = Postgres.#convertPlaceholders(sql);
        data.forEach((val, idx) => {
            const param = `$${idx + 1}`;
            const strVal = typeof val === 'string' ? `'${val.replace(/'/g, "''")}'` : String(val);
            formatted = formatted.replace(param, strVal);
        });
        return formatted;
    }

    /**
     * Converts a timestamp-like value into ISO format for PostgreSQL.
     *
     * @param {string|number|Date} timestamp
     * @returns {string}
     */
    static toDateTime(timestamp) {
        return new Date(timestamp).toISOString();
    }

    static like(str) {
        return { like: str };
    }

    static between(a, b) {
        return { between: [a, b] };
    }

    static ne(value) {
        return { not: value };
    }

    static lt(value) {
        return { '<': value };
    }

    static gt(value) {
        return { '>': value };
    }

    static lte(value) {
        return { '<=': value };
    }

    static gte(value) {
        return { '>=': value };
    }
}
